@api = http://localhost:5000

### POST SIGNUP USER
POST {{api}}/signup
Content-Type: application/json

{
    "email": "toni@toni.com",
    "password": "Toni123"
}

### POST LOGIN USER
POST {{api}}/login
Content-Type: application/json

{
    "email": "toni@toni.com",
    "password": "Toni123"
}

### GET ANNOUNCEMENT LIST
GET {{api}}/announcements

### GET ANNOUNCEMENT DETAILS
GET {{api}}/announcements/5faa6e0eb9c075ff348c95db

### POST NEW ANNOUNCEMENT
POST {{api}}/announcements
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmFhNmQ4N2I5YzA3NWZmMzQ4Yzk1ZDkiLCJpYXQiOjE2MDUwMDQ2ODMsImV4cCI6MTYzNjU0MDY4M30.3PDfflwTDkCy0cx6b0gxS0daeSYmeCB9biEzld1dl1Y
Content-Type: application/json

{
    "title": "Anuncio 1"
}

### PUT EDITTING ANNOUNCEMENT
PUT {{api}}/announcements/5faa6e0eb9c075ff348c95db
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmFhNmQ4N2I5YzA3NWZmMzQ4Yzk1ZDkiLCJpYXQiOjE2MDUwMDQ2ODMsImV4cCI6MTYzNjU0MDY4M30.3PDfflwTDkCy0cx6b0gxS0daeSYmeCB9biEzld1dl1Y
Content-Type: application/json

{
    "title": "TEST"
}

### PUT EDITTING ANNOUNCEMENT
DELETE {{api}}/announcements/5faa6e0eb9c075ff348c95db
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmFhNmQ4N2I5YzA3NWZmMzQ4Yzk1ZDkiLCJpYXQiOjE2MDUwMDQ2ODMsImV4cCI6MTYzNjU0MDY4M30.3PDfflwTDkCy0cx6b0gxS0daeSYmeCB9biEzld1dl1Y


### GET OFFER DETAILS
GET {{api}}/offers/5faa7692c6cda20de9b6a072
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmFhNmQ4N2I5YzA3NWZmMzQ4Yzk1ZDkiLCJpYXQiOjE2MDUwMDQ2ODMsImV4cCI6MTYzNjU0MDY4M30.3PDfflwTDkCy0cx6b0gxS0daeSYmeCB9biEzld1dl1Y

### POST GENERATE OFFER
POST {{api}}/offers/5faa6e0eb9c075ff348c95db
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmFhNmQ4N2I5YzA3NWZmMzQ4Yzk1ZDkiLCJpYXQiOjE2MDUwMDQ2ODMsImV4cCI6MTYzNjU0MDY4M30.3PDfflwTDkCy0cx6b0gxS0daeSYmeCB9biEzld1dl1Y
Content-Type: application/json

{
    "estimatedPrice": 2503,
    "comments": "This is a test"
}